import React from "react";

const PointNav = () => {
	return (
		<div>
			<aside
				className="
					items-start
					bg-darker
					flex
					flex-column
					flex-nowrap
					gap-8
					h-screen
					justify-center
					p-8
					text-left
					rounded-xl
					w-[28rem]"
			>
				<nav
					className="
						items-center
						flex
						flex-row
						flex-nowrap
						justify-between
						w-full"
				>
					<h2
						className="
							font-xl
							font-semibold
							text-lightest"
					>
						Priority
					</h2>
					<ul
						className="
							flex
							flex-row
							flex-nowrap
							gap-8
							items-center
							justify-center"
					>
						<li>
							<button
								alt="previous"
								className="
									border-0
									bg-[url('./components/PointNav/img/arrow-left.webp')]
									h-[3.2rem]
									w-[3.2rem]"
							></button>
						</li>
						<li>
							<h2>1</h2>
						</li>
						<li>
							<button
								alt="next"
								className="
									border-0
									bg-[url('./components/PointNav/img/arrow-right.webp')]
									h-[3.2rem]
									w-[3.2rem]"
							></button>
						</li>
					</ul>
				</nav>
				<section>
					<h3
						className="
							font-xl
							font-semibold
							pb-8
							text-lightest"
					>
						Category Name
					</h3>
					<ul
						className="
							flex
							flex-column
							flex-nowrap
							font-lightest
							font-base
							justify-center
							w-[28rem]"
					>
						<li
							className="
								h-[3.5rem]
								hover:bg-dark
								ml-[-2rem]
								pt-[1rem]
								pl-[2rem]"
						>
							<p>
								1.1 - Point Title
							</p>
						</li>
						<li
							className="
								h-[3.5rem]
								hover:bg-dark
								ml-[-2rem]
								pt-[1rem]
								pl-[2rem]"
						>
							<p>
								1.2 - Point Title
							</p>
						</li>
						<li
							className="
								h-[3.5rem]
								hover:bg-dark
								ml-[-2rem]
								pt-[1rem]
								pl-[2rem]"
						>
							<p>
								1.3 - Point Title
							</p>
						</li>
						<li
							className="
								h-[3.5rem]
								hover:bg-dark
								ml-[-2rem]
								pt-[1rem]
								pl-[2rem]"
						>
							<p>
								1.4 - Point Title
							</p>
						</li>
						<li
							className="
								h-[3.5rem]
								hover:bg-dark
								ml-[-2rem]
								pt-[1rem]
								pl-[2rem]"
						>
							<p>
								1.5 - Point Title
							</p>
						</li>
						<li
							className="
								h-[3.5rem]
								hover:bg-dark
								ml-[-2rem]
								pt-[1rem]
								pl-[2rem]"
						>
							<p>
								1.6 - Point Title
							</p>
						</li>
						<li
							className="
								h-[3.5rem]
								hover:bg-dark
								ml-[-2rem]
								pt-[1rem]
								pl-[2rem]"
						>
							<p>
								1.7 - Point Title
							</p>
						</li>
						<li
							className="
								h-[3.5rem]
								hover:bg-dark
								ml-[-2rem]
								pt-[1rem]
								pl-[2rem]"
						>
							<p>
								1.8 - Point Title
							</p>
						</li>
						<li
							className="
								h-[3.5rem]
								hover:bg-dark
								ml-[-2rem]
								pt-[1rem]
								pl-[2rem]"
						>
							<p>
								1.9 - Point Title
							</p>
						</li>
						<li
							className="
								h-[3.5rem]
								hover:bg-dark
								ml-[-2rem]
								pt-[1rem]
								pl-[2rem]"
						>
							<p>
								1.10 - Point Title
							</p>
						</li>
						<li
							className="
								h-[3.5rem]
								hover:bg-dark
								ml-[-2rem]
								pt-[1rem]
								pl-[2rem]"
						>
							<p>
								1.11 - Point Title
							</p>
						</li>
						<li
							className="
								h-[3.5rem]
								hover:bg-dark
								ml-[-2rem]
								pt-[1rem]
								pl-[2rem]"
						>
							<p>
								1.12 - Point Title
							</p>
						</li>
						<li
							className="
								h-[3.5rem]
								hover:bg-dark
								ml-[-2rem]
								pt-[1rem]
								pl-[2rem]"
						>
							<p>
								1.13 - Point Title
							</p>
						</li>
						<li
							className="
								h-[3.5rem]
								hover:bg-dark
								ml-[-2rem]
								pt-[1rem]
								pl-[2rem]"
						>
							<p>
								1.14 - Point Title
							</p>
						</li>
						<li
							className="
								h-[3.5rem]
								hover:bg-dark
								ml-[-2rem]
								pt-[1rem]
								pl-[2rem]"
						>
							<p>
								1.15 - Point Title
							</p>
						</li>
					</ul>
				</section>
			</aside>
		</div>
	);
}

export default PointNav;